### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by EricMagalhaesDelgado** [InovaFiscaliza/SCH#7]
**1ª versão de teste:**

- [x] Versão desktop;
- [x] Módulo de consulta;
- [x] Módulo de anotação offline;
- [x] Módulo de relatório restrito à geração do HTML.

**2ª versão de teste**

- [x] Atualização base SCH, criando rotina pra baixar os dois arquivos públicos do dashboard e concatená-los, até que seja disponibilizada nova base pela SGI;
- [x] Atualização base anotação (depende de definição de solução Fiscaliza+GitHub);
- [x] Relato inspeção Fiscaliza e upload de relatório p/ SEI (depende evolução lib fiscaliza).

**3ª versão de teste**

- [x] Evolução base SCH (depende SOR+SGI);
- [x] Webapp (depende de operação estável do MATLAB WebServer).

**Comment by EricMagalhaesDelgado** [comment]
Em relação à evolução da base SCH, a ORCN abriu SMTI no Processo nº 53500.063131/2024-17. Será aberto novo issue p/ tratar esse caso específico, assim que a SGI disponibilizar a base.
